version: '3'

services:
  lam:
    image: computersciencehouse/ldap-account-manager
    # build: .
    restart: always
    ports:
      - 8080:8080
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
        - LDAP_ORGANISATION=abexa
        - LDAP_DOMAIN=abexa.pe
        - "LDAP_BASE_DN=dc=abexa,dc=pe"
        - LDAP_ADMIN_PASSWORD=abexa
    volumes:
      - ./assets/ldap/ldif:/ldap-data
    ports:
        - 389:389
        - 636:636